nginx-chart:
  replicaCount: 3
  
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  
  service:
    name: nginx
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: false
